Phone number generator
KeaTesting/PersonalTestDataGeneratorBackend pull request #9
Opened 2024-10-12 19:58 UTC by victor-dat21b

Har fået lavet en masse tests til PhoneNumberGenerator.
De første test er til at teste at strukturen der bliver spyttet ud af PNG er korrekt. Disse er opdelt efter Equivalence Partitioning.

De efterfølgende er Boundary Value test med både 2 og 3 værdier. Jeg lavede 3 på dem der opstod som enkeltværdier i vores "validprefixes" og 2 Boundary approach til dem der fungere som intervaller. Testene er ikke grupperet efter Equivalence Partitioning, idet jeg følte det gav et bedre overblik at holde alle test for én værdi samlet, hvilket burde give bedre overlbik.

Jeg lagde mærke til at Bjørn har lavet hele klassen og dens metoder static static hvilket giver god mening, så jeg har indrettet mig efter dette og indkorporeret det.

2024-10-12 20:09 UTC, Troels-dat21B reviewed
Skal nok bare lige havde forklaret hvorfor de vestlige sprog med med i testene der tjekker skrift i nummeret

2024-10-12 20:09 UTC, Troels-dat21B commented on UnitTests/PhoneNumberGeneratorTests.cs
> +        //NEGATIVE General structure test 1/10
Er ikke helt med på de tests der indeholde ikke "normale skrift tegn". Er forvirret over hvorfor de er med

2024-10-14 09:13 UTC, Bjand49 commented on UnitTests/PhoneNumberGeneratorTests.cs
> +        string[] validPrefixes = PhoneNumberGenerator.validPrefixes;
I blackboxtesting må vi ikke tage listen af gyldige værdier fra klassen

2024-10-14 09:14 UTC, Bjand49 commented on UnitTests/PhoneNumberGeneratorTests.cs
> +            Assert.DoesNotContain("72", PhoneNumberGenerator.validPrefixes);
Vær sikker på at du bruger den værdi der bliver sat i toppen, istedet for at bruge værdien fra PhoneNumberGenerator

2024-10-14 09:23 UTC, Ceazer101 submitted a review, later dismissed

2024-10-14 09:27 UTC, Bjand49 requested changes
skal fikse kommentarer

2024-10-14 11:25 UTC, Bjand49 requested changes

2024-10-14 11:25 UTC, Bjand49 commented on UnitTests/PhoneNumberGeneratorTests.cs
> +        //We have run 2 boundary tests on 5 entries in the list and have a final of 20 tests.
du har stadig referencer til test amount

2024-10-14 11:25 UTC, Bjand49 commented on UnitTests/PhoneNumberGeneratorTests.cs
> +
it be empty down here eh

2024-10-14 11:36 UTC, Bjand49 approved these changes, later dismissed

2024-10-14 11:41 UTC, Bjand49 approved these changes

2024-10-14 11:43 UTC, merged